#!/usr/bin/env python3
"""Generate blueprint-schema.json from LLMTradingBlueprint Pydantic model.

Usage: python scripts/generate_blueprint_schema.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

# Ensure project root is on path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from shared.models.blueprint import LLMTradingBlueprint

# Fields that are runtime-only (not part of LLM output)
_RUNTIME_FIELDS = {
    "id", "trading_date", "generated_at", "model_provider", "model_version",
    "status", "execution_summary",
}

_RUNTIME_PLAN_FIELDS = {
    "is_entered", "entry_time", "entry_fill_prices",
    "is_exited", "exit_time", "exit_fill_prices", "realized_pnl",
}

_LEG_RUNTIME_FIELDS = {"target_entry_price", "price_tolerance"}


def _strip_runtime_fields(schema: dict) -> dict:
    """Remove runtime-only fields from the JSON schema."""
    props = schema.get("properties", {})
    required = schema.get("required", [])

    # Remove top-level runtime fields
    for field in _RUNTIME_FIELDS:
        props.pop(field, None)
        if field in required:
            required.remove(field)

    # Remove SymbolPlan runtime fields
    defs = schema.get("$defs", {})
    if "SymbolPlan" in defs:
        sp_props = defs["SymbolPlan"].get("properties", {})
        sp_required = defs["SymbolPlan"].get("required", [])
        for field in _RUNTIME_PLAN_FIELDS:
            sp_props.pop(field, None)
            if field in sp_required:
                sp_required.remove(field)

    # Remove OptionLeg runtime fields
    if "OptionLeg" in defs:
        leg_props = defs["OptionLeg"].get("properties", {})
        leg_required = defs["OptionLeg"].get("required", [])
        for field in _LEG_RUNTIME_FIELDS:
            leg_props.pop(field, None)
            if field in leg_required:
                leg_required.remove(field)

    return schema


def main():
    schema = LLMTradingBlueprint.model_json_schema()
    schema = _strip_runtime_fields(schema)

    # Add metadata
    schema["$schema"] = "https://json-schema.org/draft/2020-12/schema"
    schema["description"] = (
        "Next-day options trading blueprint generated by the trading-analysis skill"
    )

    out_path = (
        Path(__file__).resolve().parent.parent
        / "services" / "analysis_service" / "app" / "skills"
        / "trading-analysis" / "assets" / "blueprint-schema.json"
    )
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(schema, indent=2) + "\n")
    print(f"Schema written to {out_path} ({out_path.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
